name: Create Release

on:
  push:
    tags:
    - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Create Release Archive
      run: |
        zip -r "blender-asset-exporter-${{ github.ref_name }}.zip" \
            COPYING README.md blender_manifest.toml *.py

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "blender-asset-exporter-${{ github.ref_name }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
