name: Create Release

on:
  push:
    tags:
    - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write-all

    steps:
    - uses: actions/checkout@v3

    - name: Generate Changelog
      uses: smichard/conventional_changelog@2.0.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Git User Info
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'

    - name: Commit Changelog
      run: |
        git add CHANGELOG.md
        git commit -m "docs: :robot: changelog file generated" || echo "No changes to commit"
        git push origin HEAD:main

    - name: Create Release Archive
      run: |
        mkdir -p release_temp/blender-asset-exporter
        cp CHANGELOG.md COPYING README.md blender_manifest.toml *.py release_temp/blender-asset-exporter/
        zip -r "blender-asset-exporter-${{ github.ref_name }}.zip" release_temp
        rm -rf release_temp

    - name: Read Changelog Contents
      id: read_changelog
      run: |
        echo "CHANGELOG_BODY<<EOF" >> $GITHUB_ENV
        cat CHANGELOG.md >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "blender-asset-exporter-${{ github.ref_name }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: ${{ env.CHANGELOG_BODY }}
