name: Create Release

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install conventional-changelog-cli
      run: npm install -g conventional-changelog-cli

    - name: Generate Changelog
      run: conventional-changelog -p angular -i CHANGELOG.md -s --release-count 1

    - name: Create Release Archive
      run: |
        mkdir -p blender-asset-exporter
        cp CHANGELOG.md COPYING README.md blender_manifest.toml *.py blender-asset-exporter/
        zip -r "blender-asset-exporter-${{ github.ref_name }}.zip" blender-asset-exporter
        rm -rf blender-asset-exporter

    - name: Read Changelog Contents
      id: read_changelog
      run: |
        CHANGELOG_BODY=$(cat CHANGELOG.md)
        echo "changelog_body<<EOF" >> $GITHUB_ENV
        echo "$CHANGELOG_BODY" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "blender-asset-exporter-${{ github.ref_name }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: ${{ env.CHANGELOG_BODY }}
